"""
Script 04: Data Quality Report Generator
Generates a full markdown report on all datasets — row counts,
null stats, PC11 code coverage, and cross-dataset join readiness.

Usage:
    python 04_generate_data_report.py
Output: docs/data_quality_report.md
"""

import json
import pandas as pd
from pathlib import Path
from datetime import datetime

BASE_DIR = Path(__file__).resolve().parents[3]
CONFIG_PATH = Path(__file__).resolve().parents[1] / "configs" / "datasets.json"
DOCS_DIR = Path(__file__).resolve().parents[2] / "docs"
DOCS_DIR.mkdir(parents=True, exist_ok=True)
OUTPUT_PATH = DOCS_DIR / "data_quality_report.md"


def analyze_csv(path: Path, join_key: str | None) -> dict:
    try:
        df = pd.read_csv(path, low_memory=False, nrows=100_000)  # sample for large files
        full_rows = sum(1 for _ in open(path)) - 1  # fast row count

        result = {
            "rows": full_rows,
            "columns": len(df.columns),
            "null_pct": round(df.isnull().mean().mean() * 100, 2),
            "columns_list": list(df.columns),
            "join_key_present": join_key in df.columns if join_key else None,
            "join_key_nulls": None,
            "error": None,
        }

        if join_key and join_key in df.columns:
            result["join_key_nulls"] = int(df[join_key].isnull().sum())

        return result
    except Exception as e:
        return {"error": str(e)}


def main():
    with open(CONFIG_PATH) as f:
        config = json.load(f)

    lines = [
        f"# India Intelligence Engine — Data Quality Report",
        f"Generated: {datetime.now().strftime('%Y-%m-%d %H:%M')}",
        f"Base directory: `{BASE_DIR}`",
        "",
        "---",
        "",
    ]

    for dataset in config["datasets"]:
        ds_id = dataset["id"]
        source = dataset["source_file"]
        path = BASE_DIR / source
        ext = Path(source).suffix.lower()

        lines.append(f"## {dataset['name']} (`{ds_id}`)")
        lines.append(f"- **File**: `{source}`")
        lines.append(f"- **Level**: {dataset.get('level', 'N/A')}")
        lines.append(f"- **Status**: {dataset.get('status', 'N/A')}")
        lines.append(f"- **Exists**: {'Yes' if path.exists() else 'NO - FILE MISSING'}")

        if path.exists() and ext == ".csv":
            join_key = dataset.get("join_key")
            stats = analyze_csv(path, join_key)
            if stats.get("error"):
                lines.append(f"- **Error**: {stats['error']}")
            else:
                lines.append(f"- **Rows**: {stats['rows']:,}")
                lines.append(f"- **Columns**: {stats['columns']}")
                lines.append(f"- **Null %**: {stats['null_pct']}%")
                if join_key:
                    present = stats.get("join_key_present")
                    nulls = stats.get("join_key_nulls", 0)
                    lines.append(f"- **Join Key** (`{join_key}`): {'Present' if present else 'MISSING'}"
                                 + (f" | {nulls} nulls" if present else ""))
                lines.append(f"- **Columns**: `{', '.join(stats['columns_list'][:10])}`{'...' if len(stats['columns_list']) > 10 else ''}")

        elif path.exists() and ext in (".shp", ".geojson"):
            size_mb = path.stat().st_size / (1024 * 1024)
            lines.append(f"- **Size**: {size_mb:.1f} MB")

        lines.append("")

    lines.append("---")
    lines.append("*Report auto-generated by `04_generate_data_report.py`*")

    report = "\n".join(lines)
    OUTPUT_PATH.write_text(report)
    print(f"Report saved to: {OUTPUT_PATH}")


if __name__ == "__main__":
    main()
